<?php
/**
 * WebEngine CMS
 * https://webenginecms.org/
 * 
 * @version 2.0.0
 * @author Lautaro Angelico <http://lautaroangelico.com/>
 * @copyright (c) 2013-2017 Lautaro Angelico, All Rights Reserved
 * 
 * Licensed under the MIT license
 * http://opensource.org/licenses/MIT
 */

define('_WE_BANS_', WE_TABLE_PREFIX . 'WEBENGINE_BANS');
define('_WE_BANLOG_', WE_TABLE_PREFIX . 'WEBENGINE_BAN_LOG');
define('_WE_BLOCKEDIP_', WE_TABLE_PREFIX . 'WEBENGINE_BLOCKED_IP');
define('_WE_CREDITSCFG_', WE_TABLE_PREFIX . 'WEBENGINE_CREDITS_CONFIG');
define('_WE_CREDITSLOGS_', WE_TABLE_PREFIX . 'WEBENGINE_CREDITS_LOGS');
define('_WE_CRON_', WE_TABLE_PREFIX . 'WEBENGINE_CRON');
define('_WE_DOWNLOADS_', WE_TABLE_PREFIX . 'WEBENGINE_DOWNLOADS');
define('_WE_FLA_', WE_TABLE_PREFIX . 'WEBENGINE_FLA');
define('_WE_MODULES_', WE_TABLE_PREFIX . 'WEBENGINE_MODULES');
define('_WE_NEWS_', WE_TABLE_PREFIX . 'WEBENGINE_NEWS');
define('_WE_PWDCHANGE_', WE_TABLE_PREFIX . 'WEBENGINE_PASSCHANGE_REQUEST');
define('_WE_PAYPAL_', WE_TABLE_PREFIX . 'WEBENGINE_PAYPAL_TRANSACTIONS');
define('_WE_PLUGINS_', WE_TABLE_PREFIX . 'WEBENGINE_PLUGINS');
define('_WE_REGISTER_', WE_TABLE_PREFIX . 'WEBENGINE_REGISTER_ACCOUNT');
define('_WE_SESSION_', WE_TABLE_PREFIX . 'WEBENGINE_SESSION_CONTROL');
define('_WE_SRERRORLOG_', WE_TABLE_PREFIX . 'WEBENGINE_SR_ERROR_LOGS');
define('_WE_SRTRANSACTIONS_', WE_TABLE_PREFIX . 'WEBENGINE_SR_TRANSACTIONS');
define('_WE_VOTES_', WE_TABLE_PREFIX . 'WEBENGINE_VOTES');
define('_WE_VOTELOGS_', WE_TABLE_PREFIX . 'WEBENGINE_VOTE_LOGS');
define('_WE_VOTESITES_', WE_TABLE_PREFIX . 'WEBENGINE_VOTE_SITES');